name: Auto Add New Issues and PRs to Org Project

on:
  issues:
    types: [opened,reopened]
  pull_request:
    types: [opened,reopened]

jobs:
  call_add_to_project:
    uses: uitiorg/.github/.github/workflows/add-to-org-project.yml@main
    secrets: inherit
