name: Auto Add Issue/PR to Org Project

on:
  workflow_call:
    inputs:
      project-url:
        required: false
        type: string
        default: "https://github.com/orgs/uitiorg/projects/2"
    secrets:
      ADD_TO_PROJECT_PAT:
        required: false

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Add to Organization Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: ${{ inputs.project-url }}
          # github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          github-token: ${{ secrets.ORG_PROJECT_PAT }}
