name: Sync Main Merged Branch to Develop

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  sync-original-branch-to-develop:
    runs-on: self-hosted
    steps:
      - name: Extract source branch name
        run: |
          echo "SOURCE_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      - name: Checkout source branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SOURCE_BRANCH }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create PR to develop
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          base: develop
          branch: ${{ env.SOURCE_BRANCH }}
          title: "Sync `${{ env.SOURCE_BRANCH }}` → develop"
          body: |
            `${{ env.SOURCE_BRANCH }}` 브랜치가 `main`에 머지되었으므로 `develop`에도 반영합니다.

      - name: Enable auto-merge for PR
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge
