name: Sync Main Merged Branch to Develop

on:
  workflow_call:
    inputs:
      main_branch:
        description: '메인 브랜치 이름'
        required: false
        type: string
        default: 'main'
      develop_branch:
        description: '개발 브랜치 이름'
        required: false
        type: string
        default: 'develop'
  pull_request:
    types: [closed]
    branches:
      - ${{ github.event.inputs.main_branch || 'main' }}

jobs:
  sync:
    if: >
      github.event_name == 'workflow_call'
      ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: self-hosted

    steps:
      - name: Checkout 코드
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: PR 생성 & 병합
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const inputs     = github.event.inputs || {};
            const mainBr     = inputs.main_branch || (github.event.pull_request?.base.ref) || 'main';
            const developBr  = inputs.develop_branch || 'develop';

            // pull_request 이벤트인 경우 merged 여부 재확인
            if (github.event_name === 'pull_request' && !github.event.pull_request.merged) {
              console.log('PR이 merge되지 않아 스킵합니다.');
              return;
            }

            // 1) develop 브랜치에 main 브랜치 동기용 PR 생성
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Sync ${mainBr} → ${developBr} (${context.sha.substring(0,7)})`,
              head: mainBr,
              base: developBr,
              body: `자동 동기화: ${mainBr} 커밋 ${context.sha}를 ${developBr}에 반영합니다.`
            });

            // 2) 생성된 PR 자동 Merge
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              merge_method: 'merge'
            });

            console.log(`PR #${pr.number}이 ${developBr}에 merge되었습니다.`);
