name: code-review

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
      GEMINI_API_KEY:
        required: true
    inputs:
      pr_number:
        description: "Pull Request 번호"
        required: true
        type: number

jobs:
  review:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub google-genai

      - name: Run Code Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PR_NUMBER: ${{ inputs.pr_number }}
        run: python .github/scripts/code_review.py
