name: jacoco-rule

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
      min-coverage-overall:
        required: false
        type: number
        default: 30
      min-coverage-changed:
        required: false
        type: number
        default: 50

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew jacocoTestReport

      - name: Verify Jacoco Test Reports
        run: |
          echo "Checking service Jacoco Test Report:"
          if [ -f build/reports/jacoco/test/jacocoTestReport.xml ]; then
            echo "service Jacoco Test Report exists"
            ls -l build/reports/jacoco/test/
          else
            echo "server Jacoco Test Report does not exist"
            exit 1
          fi

      - name: Store error reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/

      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: '**/build/reports/jacoco'

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            **/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: ${{ inputs.min-coverage-overall }}
          min-coverage-changed-files: ${{ inputs.min-coverage-changed }}
          title: Code Coverage Report
          update-comment: true

      - name: Check coverage and fail if below threshold
        run: |
          overall=$(echo "${{ steps.jacoco.outputs.coverage-overall }}" | cut -d'.' -f1)
          changed=$(echo "${{ steps.jacoco.outputs.coverage-changed-files }}" | cut -d'.' -f1)
          
          if [ -z "$overall" ] || [ -z "$changed" ]; then
            echo "Failed to get coverage information"
            exit 1
          fi

#         주석을 해제하면 기준 이하일 때 실패하게 설정됨
#         if [ $overall -lt ${{ inputs.min-coverage-overall }} ] || [ $changed -lt ${{ inputs.min-coverage-changed }} ]; then
#           echo "Coverage is below the required threshold."
#           echo "Overall coverage: $overall%, Changed files coverage: $changed%"
#           exit 1
#         fi
