name: review-dog

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'

permissions:
  pull-requests: write
  contents: read

jobs:
  detekt:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build detekt
        run: ./gradlew detekt

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat build/reports/detekt/detekt.xml | reviewdog -f=checkstyle -name="detekt" -reporter="github-pr-review" -level="info"